apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: tripmeal
      service: db
  serviceName: db
  template:
    metadata:
      labels:
        app: tripmeal
        service: db
    spec:
      containers:
      - image: fernandosantcs/tm-db
        name: db
        env:
        - name: DATABASE_NAME
          value: "tripmealdb"
        - name: DATABASE_USER
          value: "root"
        - name: MYSQL_ROOT_PASSWORD
          value: "my-secret-pw"
        - name: DATABASE_HOST
          value: "db"
        - name: DATABASE_PORT
          value: "3306"
        - name: TRIPMEAL_KEY
          value: "my-secret-key"
        - name: SERVER_PORT
          value: "5000"
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: tripmeal-data
  volumeClaimTemplates:
  - metadata:
      name: tripmeal-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi